### ISSUE TITLE
index out of range if --column switch missing.

### ISSUE THREAD

**Issue by bsutton** [DataFoxCo/gocsv#11]
I forgot to pass the column switch to the join and got an index out of range.
It should state that a required switch is missing.

````

gocsv join --left services_with_id.csv iahproducts.csv 
panic: runtime error: index out of range

goroutine 1 [running]:
main.GetArrayFromCsvString(0x0, 0x0, 0xc42000a132, 0x594eca, 0x5)
	/Users/alden/gocsv/src/utils.go:147 +0x254
main.(*JoinSubcommand).Run(0xc42000a120, 0xc42000e170, 0x2, 0x2)
	/Users/alden/gocsv/src/join.go:51 +0x75
main.main()
	/Users/alden/gocsv/src/gocsv.go:96 +0x22d

````

**Comment by aotimme** [comment]
Good find! Fixing now.
